openapi: 3.1.0
info: { title: Swarm1 Service, version: 0.1.0 }
servers: [{ url: https://staging.example.com/api }]
paths:
  /health:
    get:
      summary: Health
      responses: {'200': { description: OK, content: { application/json: { schema: { type: object, properties: { status: { type: string }}}}}}}
components:
  schemas: {}
