name: Swarm1 CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-verify:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    # Global env (no AUV_ID needed)
    env:
      STAGING_URL: http://127.0.0.1:3000
      API_BASE:    http://127.0.0.1:3000/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Install Playwright browsers + system deps
        shell: bash
        run: npx playwright install --with-deps

      - name: Start mock server
        shell: bash
        run: node mock/server.js &

      - name: Wait for mock server
        shell: bash
        run: npx wait-on http://127.0.0.1:3000/health

      - name: Run Playwright tests
        shell: bash
        run: npx playwright test -c tests/robot/playwright/playwright.config.ts

      # ----- Lighthouse + CVF for AUV-0002 -----
      - name: Ensure perf artifact directory (AUV-0002)
        shell: bash
        run: mkdir -p runs/AUV-0002/perf

      - name: Install Lighthouse deps
        shell: bash
        run: npm i -D lighthouse chrome-launcher

      - name: Perf proof (Lighthouse) — AUV-0002
        shell: bash
        run: |
          npx lighthouse "$STAGING_URL/products.html" \
            --only-categories=performance \
            --quiet \
            --chrome-flags="--headless=new --disable-gpu --no-sandbox --allow-insecure-localhost --ignore-certificate-errors --disable-features=BlockInsecurePrivateNetworkRequests" \
            --output=json \
            --output-path="runs/AUV-0002/perf/lighthouse.json"

      - name: CVF gate — AUV-0002
        shell: bash
        run: node orchestration/cvf-check.mjs AUV-0002
      # ------------------------------------------

      # ----- Lighthouse + CVF for AUV-0003 -----
      - name: Ensure perf artifact directory (AUV-0003)
        shell: bash
        run: mkdir -p runs/AUV-0003/perf

      - name: Perf proof (Lighthouse) — AUV-0003
        shell: bash
        run: |
          npx lighthouse "$STAGING_URL/products.html" \
            --only-categories=performance \
            --quiet \
            --chrome-flags="--headless=new --disable-gpu --no-sandbox --allow-insecure-localhost --ignore-certificate-errors --disable-features=BlockInsecurePrivateNetworkRequests" \
            --output=json \
            --output-path="runs/AUV-0003/perf/lighthouse.json"

      - name: CVF gate — AUV-0003
        shell: bash
        run: node orchestration/cvf-check.mjs AUV-0003
      # ------------------------------------------

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auv-artifacts
          path: |
            runs/**
            test-results/**