name: Swarm1 CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-and-verify:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    # Global env (no AUV_ID needed)
    env:
      STAGING_URL: http://127.0.0.1:3000
      API_BASE:    http://127.0.0.1:3000/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Install Playwright browsers + system deps
        shell: bash
        run: npx playwright install --with-deps

      # ---- Router validation and tests ----
      - name: Validate router configuration
        shell: bash
        run: node mcp/router.mjs --validate
      
      - name: Run router tests
        shell: bash
        run: npm run test:router

      # ---- Autopilot runs (single source of truth) ----
      - name: AUV-0002 (autopilot)
        shell: bash
        run: node orchestration/cli.mjs AUV-0002

      - name: AUV-0003 (autopilot)
        shell: bash
        run: node orchestration/cli.mjs AUV-0003

      - name: AUV-0004 (autopilot)
        shell: bash
        run: node orchestration/cli.mjs AUV-0004

      - name: AUV-0005 (autopilot)
        shell: bash
        run: node orchestration/cli.mjs AUV-0005

      - name: Validate runbook cards
        if: always()
        shell: bash
        run: npm run validate:cards

      - name: Artifact consistency check
        if: always()
        shell: bash
        run: node orchestration/lib/artifact_consistency.mjs

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auv-artifacts
          path: |
            runs/**
            test-results/**